### ISSUE TITLE
assert_eq(a,b,) doesn't show pretty printing

### ISSUE THREAD

**Issue by Stargateur** [colin-kiegel/rust-pretty-assertions#41] opened 2020-04-10 07:00 UTC
Giving the following MCVE:

```rust
fn main() {
    #[derive(Debug, PartialEq)]
    struct Foo<'a> {
        lorem: &'a str,
        ipsum: u32,
        dolor: Result<String, String>,
    }

    let x = Some(Foo { lorem: "Hello World!", ipsum: 42, dolor: Ok("hey".to_string())});
    let y = Some(Foo { lorem: "Hello Wrold!", ipsum: 42, dolor: Ok("hey ho!".to_string())});

    pretty_assertions::assert_eq!(x, y,);
}
```

```none
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(Foo { lorem: "Hello World!", ipsum: 42, dolor: Ok("hey") })`,
 right: `Some(Foo { lorem: "Hello Wrold!", ipsum: 42, dolor: Ok("hey ho!") })`', src\main.rs:12:5
```

Add an extra comma, seem to disable everything.

**Comment by Stargateur** [comment] 2020-04-10 07:42
So, be aware that `pretty_assertions::assert_eq!(a,b,);` doesn't use the pretty print :p I'm full of sadness. don't add extra `,`

**Comment by Stargateur** [comment] 2020-04-10 08:05
Like I didn't `use pretty_assertions::assert_eq;` the line:

https://github.com/colin-kiegel/rust-pretty-assertions/blob/2f4058ac7fb5e24a923aef80851c6608b6683d0f/src/lib.rs#L113-L115

fail back to std implementation, I think we need to use a internal second macro to avoid repetition code and the bug. But I'm don't know much about rust declarative macro.

Same problem will happen for `assert_ne!`:

https://github.com/colin-kiegel/rust-pretty-assertions/blob/2f4058ac7fb5e24a923aef80851c6608b6683d0f/src/lib.rs#L147-L155

**Comment by spenserblack** [comment] 2020-08-26 16:59
This should do it (it's probably what was intended).
```diff
 ($left:expr , $right:expr,) => ({ 
-    assert_eq!($left, $right)
+    $crate::assert_eq!($left, $right)
 }); 
```
But the optional `,` can also be captured with this macro pattern.
```rust
($left:expr, $right:expr $(,)?) => { /* do stuff */ }
```

**Comment by gmoshkin** [comment] 2020-10-27 17:58
Spent a couple of hours today finding out this bug :(

**Comment by tommilligan** [comment] 2021-02-10 22:41
Thanks for reporting this. A fix has been merged and will be in the next release.

**Closed** 2021-02-10 22:41 UTC
