### ISSUE TITLE
false warning of `use` when using pretty_assertions with test module

### ISSUE THREAD

**Issue by hoangtranwork** [colin-kiegel/rust-pretty-assertions#8] opened 2017-06-01 17:09 UTC
I've try using *pretty_assertions* on a fresh library cargo project. The test module in such project has a `use super::my_module;` statement. After adding those `#[macro_use] extern crate pretty_assertions;` stuff in (following the guide), it causes false warning of the `use` statement.
Here's the asciinema recording: 
[![asciicast](https://asciinema.org/a/123025.png)](https://asciinema.org/a/123025)
I'm new to rust and I'm not sure if this is a specific issue of *pretty_assertions* or not, just sharing my observation.
I'm using latest stable rust as of today.

**Comment by colin-kiegel** [comment] 2017-06-02 00:34
@hoangtranwork Welcome to Rust and thank you for the detailed report. :-)

I think this is not specific to _pretty_assertions_. Could you please change the order if some lines from

```rust
#[cfg(test)]
#[macro_use]
extern crate pretty_assertions;

mod tests { /* ... */ }
```

.. to

```rust
#[macro_use]
extern crate pretty_assertions;

#[cfg(test)]
mod tests { /* ... */ }
```

I inserted new lines to highlight the effect of `#[...]` statements. Please report back, if this solves your issue. Thank you.

**Comment by hoangtranwork** [comment] 2017-06-06 13:48
@colin-kiegel thank you and sorry for the delay, I didn't notice that github email notification doesn't work with non-watching repo.

I've tried you suggestion along with some others experiments with the postion of `#[macro_use]`, which dependencies section to use in `Cargo.toml`, and even using the `extern crate` line alone without `#[macro_use]`. I can find only 1 case that there's no false warning of the `use` statement:
* In `Cargo.toml`, don't use `[dev-dependencies]`
```toml
[dependencies]
pretty_assertions = "0.2.0"
```
* In `lib.rs`, put `#[macro_use]...` above `#[cfg(test)]` as you suggested
```rust
#[macro_use]
extern crate pretty_assertions;

#[cfg(test)]
mod tests { /* ... */ }
```
No more false warning of `use super::my_mod` any more, BUT, there's a new false warning of the line `#[macro_use]`, which is neccessary.

After playing back & forth for a while now the sample project is a mess, and also I'm lost :D now. Will try to put up a detail report of each case later if needed. Note that there's case that is compile Error too, not just warning.

**Comment by colin-kiegel** [comment] 2017-06-24 19:22
@hoangtranwork you were already very close to the solution :-)

```rust
#[cfg(test)] // <-- you have to add this line both HERE
#[macro_use]
extern crate pretty_assertions;

#[cfg(test)] // ... and HERE
mod tests {
```

In your attempts you only had this line in one of these places, but not in both.

I'll close this, since it's not a bug.

**Closed by colin-kiegel** 2017-06-24 19:22 UTC

**Comment by hoangtranwork** [comment] 2017-06-25 10:37
Thank you, it works wells now. Though the double specifying of `#[cfg(test)]` seems redundant, not sure if this is a specific pretty_assertions issue or just general rust issue

**Comment by colin-kiegel** [comment] 2017-06-25 10:41
@hoangtranwork this behaviour is rust specific, `#[cfg(test)]` and other attributes always only affect the next item or statement. Glad I could help you. :-)
